[theme]
primaryColor = "#66DD99"             # Color principal (verde menta aproximado)
backgroundColor = "#FFFFFF"          # Fondo blanco
secondaryBackgroundColor = "#F7F7F7" # Un tono blanco/gris muy claro
textColor = "#000000"                # Texto negro
font = "sans serif"
